### ISSUE TITLE
Error while running gsnw.py

### ISSUE THREAD

**Issue by gpxlnx** [retkoussa/gsnw#1]
When I run this script the error below show me.

Traceback (most recent call last):
  File "gsnw.py", line 11, in <module>
    from seleniumwire import webdriver
  File "/tmp/ax/gsnw/.juca/lib/python3.8/site-packages/seleniumwire/webdriver.py", line 28, in <module>
    from seleniumwire import backend, utils
  File "/tmp/ax/gsnw/.juca/lib/python3.8/site-packages/seleniumwire/backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "/tmp/ax/gsnw/.juca/lib/python3.8/site-packages/seleniumwire/server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "/tmp/ax/gsnw/.juca/lib/python3.8/site-packages/seleniumwire/handler.py", line 5, in <module>
    from seleniumwire import har
  File "/tmp/ax/gsnw/.juca/lib/python3.8/site-packages/seleniumwire/har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "/tmp/ax/gsnw/.juca/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "/tmp/ax/gsnw/.juca/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/net/tls.py", line 15, in <module>
    import seleniumwire.thirdparty.mitmproxy.options
  File "/tmp/ax/gsnw/.juca/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/options.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import optmanager
  File "/tmp/ax/gsnw/.juca/lib/python3.8/site-packages/seleniumwire/thirdparty/mitmproxy/optmanager.py", line 9, in <module>
    import blinker._saferef
ModuleNotFoundError: No module named 'blinker._saferef'

**Comment by retkoussa** [comment]
Hi!

May you please try to run: 
```
pip install blinker
```

Should fix the problem

**Comment by LeviAckerman666** [comment]
I have the same problem  and I tried with pip install blinker
Requirement already satisfied: blinker in /usr/lib/python3/dist-packages (1.8.2)
and..

import blinker._saferef
ModuleNotFoundError: No module named 'blinker._saferef'

**Comment by spector012** [comment]
here's a fix 
`pip install blinker==1.4`

**Comment by retkoussa** [comment]
> here's a fix `pip install blinker==1.4`

@LeviAckerman666 @gpxlnx 
Can you confirm that @spector012's fix works?

**Comment by retkoussa** [comment]
I'll close this for now, if anything comes up please let me know.
