### ISSUE TITLE
Chrome session not created

### ISSUE THREAD

**Issue by dsdevsw** [retkoussa/gsnw#4]
I'm logged in Github in Chrome browser and I checked the path 'C:\\Users\\{current_user}\\AppData\\Local\\Google\\Chrome\\User Data"' as valid for my pc (as stated in your gsnw.py file) but when I enter the query `python3 gsnw.py <my_word> output.txt -silent`, this error appears:

Traceback (most recent call last):
  File "C:\Users\super\Downloads\tools\gsnw\gsnw.py", line 133, in <module>
    main()
  File "C:\Users\super\Downloads\tools\gsnw\gsnw.py", line 116, in main
    matched_words = search_github(search_query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\super\Downloads\tools\gsnw\gsnw.py", line 63, in search_github
    driver = webdriver.Chrome(service=Service(), options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\seleniumwire\webdriver.py", line 218, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from unknown error: cannot create default profile directory
Stacktrace:
        GetHandleVerifier [0x0038EC13+23731]
        (No symbol) [0x0031C394]
        (No symbol) [0x001FBE63]
        (No symbol) [0x0022FA57]
        (No symbol) [0x00229FBA]
        (No symbol) [0x002270F9]
        (No symbol) [0x0026B449]
        (No symbol) [0x0026AC0A]
        (No symbol) [0x00261BF6]
        (No symbol) [0x00233F35]
        (No symbol) [0x00234EBD]
        GetHandleVerifier [0x0066F0D3+3039603]
        GetHandleVerifier [0x00682DEA+3120778]
        GetHandleVerifier [0x0067B592+3089970]
        GetHandleVerifier [0x004243B0+635984]
        (No symbol) [0x00324DCD]
        (No symbol) [0x00322068]
        (No symbol) [0x00322205]
        (No symbol) [0x00314FD0]
        BaseThreadInitThunk [0x75BA7BA9+25]
        RtlInitializeExceptionChain [0x7744C0CB+107]
        RtlClearBits [0x7744C04F+191]

Sorry if this question is stupid, I don't know what I'm doing wrong... what exactly you mean with "# Make sure you're logged in to Github on the specificed Chrome Profile", I'm logged in while using gsnw, not sure what user session isn't created :(
Thank you.

**Comment by retkoussa** [comment]
Hello,

Please pull the new changes and make sure you do not have any chrome instances running when running the tool.

**Comment by dsdevsw** [comment]
Hello, thank you for answering. I deleted everything and started fresh following your instructions but the error persisted. So, I tried to modify parts of the code, just change some things to see if something different could happen. 

For example, I disabled with a comment the line `#current_user = os.getlogin()` and ran the script, but a new error appeared:

```
Traceback (most recent call last):
  File "C:\Users\super\Downloads\tools\gsnw\gsnw.py", line 137, in <module>
    main()
  File "C:\Users\super\Downloads\tools\gsnw\gsnw.py", line 120, in main
    matched_words = search_github(search_query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\super\Downloads\tools\gsnw\gsnw.py", line 58, in search_github
    chrome_options.add_argument(f"--user-data-dir=C:\\Users\\{current_user}\\AppData\\Local\\Google\\Chrome\\User Data")
                                                              ^^^^^^^^^^^^
NameError: name 'current_user' is not defined
```

Then, I changed `{current_user}` to `super` on the line `C:\\Users\\{current_user}\\AppData\\Local\\Google\\Chrome\\User Data")` . The script worked and I got an output file with 74 results!!! 

I think the problem is with my Github username being different from my computer username?? I don't know. Everything worked fine until I tried a new search, I got 48 results and then stopped with a new thing ... ?
```

        [x] UserSeed.cs
        [x] UserSeedDataTemplate.txt
        [x] UserSessionApi.md
Encountered a stale element, continuing...
Encountered a stale element, continuing...
Encountered a stale element, continuing...
Encountered a stale element, continuing...
Encountered a stale element, continuing...

```
Same as issue #5
